name: CI

on:
  # Triggers the workflow on push or pull request events on the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Can be triggered manually through Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out repository
      - uses: actions/checkout@v2

      - name: Create CI .env file
        run: |
          echo POSTGRES_USER=user > .env
          echo POSTGRES_DB=lukuvinkkikirjasto >> .env
          echo POSTGRES_PASSWORD=password >> .env
          echo POSTGRES_HOSTNAME=lukuvinkkikirjasto-db >> .env
          echo POSTGRES_PORT=5432 >> .env
          echo SECRET=secret >> .env
          echo DATABASE_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOSTNAME}:${POSTGRES_PORT}/${POSTGRES_DB} >> .env

      - name: Build Docker development container
        run: docker-compose build

      - name: Run pylint on src
        run: docker-compose run --no-deps --rm app poetry run invoke pylint
