name: CI-PR

on:
  # Triggers the workflow on push or pull request events on the main branch
  pull_request:
    branches: [ main ]

  # Can be triggered manually through Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out repository
      - uses: actions/checkout@v2

      - name: Create CI .env file
        run: |
          echo POSTGRES_USER=user > .env
          echo POSTGRES_DB=lukuvinkkikirjasto >> .env
          echo POSTGRES_PASSWORD=password >> .env
          echo POSTGRES_HOSTNAME=lukuvinkkikirjasto-db >> .env
          echo POSTGRES_PORT=5432 >> .env
          echo SECRET=secret >> .env
          echo "DATABASE_URI=postgresql://\${POSTGRES_USER}:\${POSTGRES_PASSWORD}@\${POSTGRES_HOSTNAME}:\${POSTGRES_PORT}/\${POSTGRES_DB}" >> .env

      - name: Build Docker development container
        run: docker-compose --profile test build

      - name: Run pylint on src
        run: docker-compose run --no-deps --rm app poetry run invoke pylint

      - name: Run Selenium tests in Docker
        run: docker-compose --profile test up --exit-code-from test

      - name: Run unittests in Docker
        run: docker-compose -f docker-compose.test.yml up --abort-on-container-exit --exit-code-from testapp #&& docker-compose -f docker-compose.test.yml down -v
    
      - name: tell me something cool
        run: cd documentation/test_reports && echo "$(ls -la)" &&  cd ../..

      - name: Deploy test reports to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./documentation/test_reports
          destination_dir: commit-${{ github.sha }}

      - name: Comment test report links to PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: "Test results: [Unittest report](https://prtopi.github.io/lukuvinkkikirjasto/commit-${{ github.sha }}/unittests/index.html) - [Robot test report](https://prtopi.github.io/lukuvinkkikirjasto/commit-${{ github.sha }}/robot/report.html)"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}